Ensure setup and migrate scripts fail if any one step fails.

diff --git a/warpdrive/etc/warpdrive-setup b/warpdrive/etc/warpdrive-setup
--- a/warpdrive/etc/warpdrive-setup
+++ b/warpdrive/etc/warpdrive-setup
@@ -4,6 +4,20 @@ if [ x"$WARPDRIVE_DEBUG" != x"" ]; then
     set -x
 fi
 
+# Ensure that any failure within this script or a user provided script
+# causes this script to fail immediately. This eliminates the need to
+# check individual statuses for anything which is run and prematurely
+# exit. Note that the feature of bash to exit in this way isn't
+# foolproof. Ensure that you heed any advice in:
+#
+#   http://mywiki.wooledge.org/BashFAQ/105
+#   http://fvue.nl/wiki/Bash:_Error_handling
+#
+# and use best practices to ensure that failures are always detected.
+# Any user supplied scripts should also use this failure mode.
+
+set -eo pipefail
+
 # Setup the environment if not already done.
 
 if [ x"$WARPDRIVE_ACTION" = x"" ]; then
